services:
  postgres:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hellotalk
      POSTGRES_PASSWORD: hellotalk
      POSTGRES_DB: hellotalk
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: